name: remote-sensing-change-monitor
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - xarray
  - rioxarray
  - rasterio
  - gdal
  - geopandas
  - shapely
  - pyproj
  - fiona
  - pystac-client
  - stackstac
  - dask
  - distributed
  - matplotlib
  - folium
  - leafmap
  - streamlit
  - pip:
      - streamlit-folium
      - streamlit-image-comparison
      - matplotlib-scalebar
